use non-created cluster

diff --git a/steps/cloud/azure/update-kubeconfig.yml b/steps/cloud/azure/update-kubeconfig.yml
--- a/steps/cloud/azure/update-kubeconfig.yml
+++ b/steps/cloud/azure/update-kubeconfig.yml
@@ -9,19 +9,21 @@ steps:
     set -euo pipefail
     set -x
 
-    region=${{ parameters.region }}
+    # region=${{ parameters.region }}
 
-    aks_name=$(az resource list --resource-type Microsoft.ContainerService/managedClusters --location $region \
-      --query "[?(tags.run_id == '${RUN_ID}' && tags.role == '$ROLE')].name" --output tsv)
+    # aks_name=$(az resource list --resource-type Microsoft.ContainerService/managedClusters --location $region \
+    #   --query "[?(tags.run_id == '${RUN_ID}' && tags.role == '$ROLE')].name" --output tsv)
 
-    aks_rg=$(az resource list --resource-type Microsoft.ContainerService/managedClusters --location $region \
-      --query "[?(tags.run_id == '${RUN_ID}' && tags.role == '$ROLE')].resourceGroup" --output tsv)
+    # aks_rg=$(az resource list --resource-type Microsoft.ContainerService/managedClusters --location $region \
+    #   --query "[?(tags.run_id == '${RUN_ID}' && tags.role == '$ROLE')].resourceGroup" --output tsv)
 
-    if [ -z "$aks_name" ]; then
-        echo "##vso[task.logissue type=error;] No AKS instance with role $ROLE and tag $RUN_ID found in region $region."
-        exit 1
-    fi
-    az aks get-credentials -n $aks_name -g $aks_rg
+    # if [ -z "$aks_name" ]; then
+    #     echo "##vso[task.logissue type=error;] No AKS instance with role $ROLE and tag $RUN_ID found in region $region."
+    #     exit 1
+    # fi
+    # az aks get-credentials -n $aks_name -g $aks_rg
+
+    az aks get-credentials -n $CLUSTER_NAME -g $RESOURCE_GROUP
   env:
     ROLE: ${{ parameters.role }}
   displayName: "Update kubeconfig"
