[feat] add utilities on worker pool creation etc (#1183)
- Update `CreateNodePool` to allow `--no-wait`
- Add `PlanNodePools` function to decide pool config based on max node
per pool
- Add `WaitForAllWorkerNodesReady` to wait for pools + nodes to be ready
- Updated existing pipelines with usage of `CreateNodePool`

diff --git a/kcl/ccp_team/hyperscale_apiserver_executing_seats/pipeline.yaml b/kcl/ccp_team/hyperscale_apiserver_executing_seats/pipeline.yaml
--- a/kcl/ccp_team/hyperscale_apiserver_executing_seats/pipeline.yaml
+++ b/kcl/ccp_team/hyperscale_apiserver_executing_seats/pipeline.yaml
@@ -142,7 +142,18 @@ jobs:
       azureSubscription: Azure-for-Telescope-internal
       scriptType: bash
       scriptLocation: inlineScript
-      inlineScript: "set -exo pipefail\n\naz aks nodepool add \\\n  --cluster-name \"stg-H8-hyperscale-apiserver-seats\" \\\n  --resource-group \"$(RUN_ID)\" \\\n  --subscription \"b8ceb4e5-f05b-4562-a9f5-14acb1f24219\" \\\n  --name \"cl2pool\" \\\n  --node-count 10 \\\n  --node-vm-size \"Standard_D16S_v4\" \\\n  --mode User \\\n  --node-taints cl2pool=true:NoSchedule \\\n  \n"
+      inlineScript: |
+        set -exo pipefail
+
+        az aks nodepool add \
+          --cluster-name "stg-H8-hyperscale-apiserver-seats" \
+          --resource-group "$(RUN_ID)" \
+          --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219" \
+          --name "cl2pool" \
+          --node-count 10 \
+          --node-vm-size "Standard_D16S_v4" \
+          --mode User \
+          --node-taints cl2pool=true:NoSchedule
     displayName: Create node pool cl2pool
   - task: AzureCLI@2
     inputs:
@@ -160,15 +171,15 @@ jobs:
             --name "cl2pool" \
             --query "provisioningState" \
             --output tsv)
-          echo "Node pool provisioning state: $STATE"
+          echo "Node pool cl2pool provisioning state: $STATE"
           if [ "$STATE" = "Succeeded" ]; then
-            echo "Node pool is ready."
+            echo "Node pool cl2pool is ready."
             break
           elif [ "$STATE" = "Failed" ] || [ "$STATE" = "Canceled" ]; then
-            echo "Node pool failed with state: $STATE."
+            echo "Node pool cl2pool failed with state: $STATE."
             exit 1
           else
-            echo "Provisioning state: $STATE. Retry in 30 seconds"
+            echo "Node pool cl2pool provisioning state: $STATE. Retry in 30 seconds"
           fi
           sleep 30
         done
@@ -208,15 +219,15 @@ jobs:
             --name "kwokpool" \
             --query "provisioningState" \
             --output tsv)
-          echo "Node pool provisioning state: $STATE"
+          echo "Node pool kwokpool provisioning state: $STATE"
           if [ "$STATE" = "Succeeded" ]; then
-            echo "Node pool is ready."
+            echo "Node pool kwokpool is ready."
             break
           elif [ "$STATE" = "Failed" ] || [ "$STATE" = "Canceled" ]; then
-            echo "Node pool failed with state: $STATE."
+            echo "Node pool kwokpool failed with state: $STATE."
             exit 1
           else
-            echo "Provisioning state: $STATE. Retry in 30 seconds"
+            echo "Node pool kwokpool provisioning state: $STATE. Retry in 30 seconds"
           fi
           sleep 30
         done
diff --git a/kcl/ccp_team/hyperscale_pod_scheduling/pipeline.yaml b/kcl/ccp_team/hyperscale_pod_scheduling/pipeline.yaml
--- a/kcl/ccp_team/hyperscale_pod_scheduling/pipeline.yaml
+++ b/kcl/ccp_team/hyperscale_pod_scheduling/pipeline.yaml
@@ -137,7 +137,18 @@ stages:
         azureSubscription: Azure-for-Telescope-internal
         scriptType: bash
         scriptLocation: inlineScript
-        inlineScript: "set -exo pipefail\n\naz aks nodepool add \\\n  --cluster-name \"stg-H2-hyperscale-pod-scheduling-rate\" \\\n  --resource-group \"$(RUN_ID)\" \\\n  --subscription \"b8ceb4e5-f05b-4562-a9f5-14acb1f24219\" \\\n  --name \"cl2pool\" \\\n  --node-count 1 \\\n  --node-vm-size \"Standard_D8S_v4\" \\\n  --mode User \\\n  --node-taints cl2pool=true:NoSchedule \\\n  \n"
+        inlineScript: |
+          set -exo pipefail
+
+          az aks nodepool add \
+            --cluster-name "stg-H2-hyperscale-pod-scheduling-rate" \
+            --resource-group "$(RUN_ID)" \
+            --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219" \
+            --name "cl2pool" \
+            --node-count 1 \
+            --node-vm-size "Standard_D8S_v4" \
+            --mode User \
+            --node-taints cl2pool=true:NoSchedule
       displayName: Create node pool cl2pool
     - task: AzureCLI@2
       inputs:
@@ -155,15 +166,15 @@ stages:
               --name "cl2pool" \
               --query "provisioningState" \
               --output tsv)
-            echo "Node pool provisioning state: $STATE"
+            echo "Node pool cl2pool provisioning state: $STATE"
             if [ "$STATE" = "Succeeded" ]; then
-              echo "Node pool is ready."
+              echo "Node pool cl2pool is ready."
               break
             elif [ "$STATE" = "Failed" ] || [ "$STATE" = "Canceled" ]; then
-              echo "Node pool failed with state: $STATE."
+              echo "Node pool cl2pool failed with state: $STATE."
               exit 1
             else
-              echo "Provisioning state: $STATE. Retry in 30 seconds"
+              echo "Node pool cl2pool provisioning state: $STATE. Retry in 30 seconds"
             fi
             sleep 30
           done
@@ -217,15 +228,15 @@ stages:
               --name "kwokpool" \
               --query "provisioningState" \
               --output tsv)
-            echo "Node pool provisioning state: $STATE"
+            echo "Node pool kwokpool provisioning state: $STATE"
             if [ "$STATE" = "Succeeded" ]; then
-              echo "Node pool is ready."
+              echo "Node pool kwokpool is ready."
               break
             elif [ "$STATE" = "Failed" ] || [ "$STATE" = "Canceled" ]; then
-              echo "Node pool failed with state: $STATE."
+              echo "Node pool kwokpool failed with state: $STATE."
               exit 1
             else
-              echo "Provisioning state: $STATE. Retry in 30 seconds"
+              echo "Node pool kwokpool provisioning state: $STATE. Retry in 30 seconds"
             fi
             sleep 30
           done
@@ -439,7 +450,18 @@ stages:
         azureSubscription: Azure-for-Telescope-internal
         scriptType: bash
         scriptLocation: inlineScript
-        inlineScript: "set -exo pipefail\n\naz aks nodepool add \\\n  --cluster-name \"stg-H4-hyperscale-pod-scheduling-rate\" \\\n  --resource-group \"$(RUN_ID)\" \\\n  --subscription \"b8ceb4e5-f05b-4562-a9f5-14acb1f24219\" \\\n  --name \"cl2pool\" \\\n  --node-count 1 \\\n  --node-vm-size \"Standard_D8S_v4\" \\\n  --mode User \\\n  --node-taints cl2pool=true:NoSchedule \\\n  \n"
+        inlineScript: |
+          set -exo pipefail
+
+          az aks nodepool add \
+            --cluster-name "stg-H4-hyperscale-pod-scheduling-rate" \
+            --resource-group "$(RUN_ID)" \
+            --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219" \
+            --name "cl2pool" \
+            --node-count 1 \
+            --node-vm-size "Standard_D8S_v4" \
+            --mode User \
+            --node-taints cl2pool=true:NoSchedule
       displayName: Create node pool cl2pool
     - task: AzureCLI@2
       inputs:
@@ -457,15 +479,15 @@ stages:
               --name "cl2pool" \
               --query "provisioningState" \
               --output tsv)
-            echo "Node pool provisioning state: $STATE"
+            echo "Node pool cl2pool provisioning state: $STATE"
             if [ "$STATE" = "Succeeded" ]; then
-              echo "Node pool is ready."
+              echo "Node pool cl2pool is ready."
               break
             elif [ "$STATE" = "Failed" ] || [ "$STATE" = "Canceled" ]; then
-              echo "Node pool failed with state: $STATE."
+              echo "Node pool cl2pool failed with state: $STATE."
               exit 1
             else
-              echo "Provisioning state: $STATE. Retry in 30 seconds"
+              echo "Node pool cl2pool provisioning state: $STATE. Retry in 30 seconds"
             fi
             sleep 30
           done
@@ -519,15 +541,15 @@ stages:
               --name "kwokpool" \
               --query "provisioningState" \
               --output tsv)
-            echo "Node pool provisioning state: $STATE"
+            echo "Node pool kwokpool provisioning state: $STATE"
             if [ "$STATE" = "Succeeded" ]; then
-              echo "Node pool is ready."
+              echo "Node pool kwokpool is ready."
               break
             elif [ "$STATE" = "Failed" ] || [ "$STATE" = "Canceled" ]; then
-              echo "Node pool failed with state: $STATE."
+              echo "Node pool kwokpool failed with state: $STATE."
               exit 1
             else
-              echo "Provisioning state: $STATE. Retry in 30 seconds"
+              echo "Node pool kwokpool provisioning state: $STATE. Retry in 30 seconds"
             fi
             sleep 30
           done
@@ -741,7 +763,18 @@ stages:
         azureSubscription: Azure-for-Telescope-internal
         scriptType: bash
         scriptLocation: inlineScript
-        inlineScript: "set -exo pipefail\n\naz aks nodepool add \\\n  --cluster-name \"stg-H8-hyperscale-pod-scheduling-rate\" \\\n  --resource-group \"$(RUN_ID)\" \\\n  --subscription \"b8ceb4e5-f05b-4562-a9f5-14acb1f24219\" \\\n  --name \"cl2pool\" \\\n  --node-count 1 \\\n  --node-vm-size \"Standard_D8S_v4\" \\\n  --mode User \\\n  --node-taints cl2pool=true:NoSchedule \\\n  \n"
+        inlineScript: |
+          set -exo pipefail
+
+          az aks nodepool add \
+            --cluster-name "stg-H8-hyperscale-pod-scheduling-rate" \
+            --resource-group "$(RUN_ID)" \
+            --subscription "b8ceb4e5-f05b-4562-a9f5-14acb1f24219" \
+            --name "cl2pool" \
+            --node-count 1 \
+            --node-vm-size "Standard_D8S_v4" \
+            --mode User \
+            --node-taints cl2pool=true:NoSchedule
       displayName: Create node pool cl2pool
     - task: AzureCLI@2
       inputs:
@@ -759,15 +792,15 @@ stages:
               --name "cl2pool" \
               --query "provisioningState" \
               --output tsv)
-            echo "Node pool provisioning state: $STATE"
+            echo "Node pool cl2pool provisioning state: $STATE"
             if [ "$STATE" = "Succeeded" ]; then
-              echo "Node pool is ready."
+              echo "Node pool cl2pool is ready."
               break
             elif [ "$STATE" = "Failed" ] || [ "$STATE" = "Canceled" ]; then
-              echo "Node pool failed with state: $STATE."
+              echo "Node pool cl2pool failed with state: $STATE."
               exit 1
             else
-              echo "Provisioning state: $STATE. Retry in 30 seconds"
+              echo "Node pool cl2pool provisioning state: $STATE. Retry in 30 seconds"
             fi
             sleep 30
           done
@@ -821,15 +854,15 @@ stages:
               --name "kwokpool" \
               --query "provisioningState" \
               --output tsv)
-            echo "Node pool provisioning state: $STATE"
+            echo "Node pool kwokpool provisioning state: $STATE"
             if [ "$STATE" = "Succeeded" ]; then
-              echo "Node pool is ready."
+              echo "Node pool kwokpool is ready."
               break
             elif [ "$STATE" = "Failed" ] || [ "$STATE" = "Canceled" ]; then
-              echo "Node pool failed with state: $STATE."
+              echo "Node pool kwokpool failed with state: $STATE."
               exit 1
             else
-              echo "Provisioning state: $STATE. Retry in 30 seconds"
+              echo "Node pool kwokpool provisioning state: $STATE. Retry in 30 seconds"
             fi
             sleep 30
           done
