Update new-pipeline-test.yml for Azure Pipelines

diff --git a/pipelines/system/new-pipeline-test.yml b/pipelines/system/new-pipeline-test.yml
--- a/pipelines/system/new-pipeline-test.yml
+++ b/pipelines/system/new-pipeline-test.yml
@@ -1,6 +1,6 @@
 stages:
-- stage: azureeastus2
-  displayName: azureeastus2
+- stage: azeastus2
+  displayName: azeastus2
   jobs:
   - job: setup
     displayName: Setup resources
@@ -46,17 +46,29 @@ stages:
     - script: |
         set -eu
 
-        echo "login to Azure in eastus2"
+        echo "login to Azure in $REGION"
         az login --service-principal --tenant $(TENANT_ID) -u $(SP_CLIENT_ID) --federated-token $(SP_ID_TOKEN) --allow-no-subscriptions
-        az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
-        az config set defaults.location="eastus2"
+        az account set --subscription "$AZURE_SP_SUBSCRIPTION_ID"
+        az config set defaults.location="$REGION"
         az account show
       displayName: Azure Login
+      env:
+        REGION: eastus2
+        AZURE_SP_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
     - script: |-
         echo "##vso[task.setvariable variable=TERRAFORM_WORKING_DIRECTORY]$(Pipeline.Workspace)/s/modules/terraform/azure"
         echo "Terraform Working Directory: $(Pipeline.Workspace)/s/modules/terraform/azure"
       displayName: Set Terraform Working Directory
+      condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
     - script: |-
+        set -eu
+
+        echo "##vso[task.setvariable variable=MULTI_REGION]false"
+        echo "##vso[task.setvariable variable=REGIONAL_CONFIG]{"eastus2": {"TERRAFORM_INPUT_FILE": "$(Pipeline.Workspace)/s/scenarios/perf-eval/job-scheduling/terraform-inputs/azure.tfvars"}}"
+      displayName: Set Terraform Input File
+      condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+    - script: |-
+        terraform_user_data_path=$(Pipeline.Workspace)/s/scenarios/perf-eval/job-scheduling/scripts/user_data
         echo $(Pipeline.Workspace)/s/scenarios/perf-eval/job-scheduling/scripts/user_data
 
         if [ -d "$(Pipeline.Workspace)/s/scenarios/perf-eval/job-scheduling/scripts/user_data" ]; then
@@ -71,15 +83,19 @@ stages:
         if [[ "${DEBUG,,}" =~ "true" ]]; then
             set -x
         fi
-        echo "Regional Configuration {"\"eastus2\"": {"\"TERRAFORM_INPUT_FILE\"": "\"$(Pipeline.Workspace)/s/scenarios/perf-eval/job-scheduling/terraform-inputs/azure.tfvars\"", "\"TERRAFORM_INPUT_VARIABLES\"": "{\"run_id\": \"$(RUN_ID)\", \"region\": \"eastus2\", \"aks_sku_tier\": \"$AKS_SKU_TIER\", \"aks_kubernetes_version\": \"$KUBERNETES_VERSION\", \"aks_network_policy\": \"$NETWORK_POLICY\", \"aks_network_dataplane\": \"$NETWORK_DATAPLANE\", \"k8s_machine_type\": \"$K8S_MACHINE_TYPE\", \"k8s_os_disk_type\": \"$K8S_OS_DISK_TYPE\", \"aks_custom_headers\": [\"$AKS_CLI_CUSTOM_HEADERS\"], \"aks_cli_system_node_pool\": \"$SYSTEM_NODE_POOL\", \"aks_cli_user_node_pool\": \"$USER_NODE_POOL\"}"}}"
-        echo "##vso[task.setvariable variable=MULTI_REGION]false"
-        echo "##vso[task.setvariable variable=TERRAFORM_REGIONAL_CONFIG]{"\"eastus2\"": {"\"TERRAFORM_INPUT_FILE\"": "\"$(Pipeline.Workspace)/s/scenarios/perf-eval/job-scheduling/terraform-inputs/azure.tfvars\"", "\"TERRAFORM_INPUT_VARIABLES\"": "{\"run_id\": \"$(RUN_ID)\", \"region\": \"eastus2\", \"aks_sku_tier\": \"$AKS_SKU_TIER\", \"aks_kubernetes_version\": \"$KUBERNETES_VERSION\", \"aks_network_policy\": \"$NETWORK_POLICY\", \"aks_network_dataplane\": \"$NETWORK_DATAPLANE\", \"k8s_machine_type\": \"$K8S_MACHINE_TYPE\", \"k8s_os_disk_type\": \"$K8S_OS_DISK_TYPE\", \"aks_custom_headers\": [\"$AKS_CLI_CUSTOM_HEADERS\"], \"aks_cli_system_node_pool\": \"$SYSTEM_NODE_POOL\", \"aks_cli_user_node_pool\": \"$USER_NODE_POOL\"}"}}"
+        config_vars='{"eastus2": {"TERRAFORM_INPUT_VARIABLES": {"run_id": "$(RUN_ID)", "region": "eastus2", "aks_sku_tier": "$AKS_SKU_TIER", "aks_kubernetes_version": "$KUBERNETES_VERSION", "aks_network_policy": "$NETWORK_POLICY", "aks_network_dataplane": "$NETWORK_DATAPLANE", "k8s_machine_type": "$K8S_MACHINE_TYPE", "k8s_os_disk_type": "$K8S_OS_DISK_TYPE", "aks_custom_headers": ["$AKS_CLI_CUSTOM_HEADERS"], "aks_cli_system_node_pool": "$SYSTEM_NODE_POOL", "aks_cli_user_node_pool": "$USER_NODE_POOL"}}}'
+        echo "regional_config: $(REGIONAL_CONFIG)"
+        echo "config_vars: $config_vars"
+        merged=$(jq -s '.[0] * .[1]' <(echo "$(REGIONAL_CONFIG)") <(echo "$config_vars"))
+        echo "merged config $merged"
+
+        echo "Final regional config: {"eastus2": {"TERRAFORM_INPUT_VARIABLES": {"run_id": "$(RUN_ID)", "region": "eastus2", "aks_sku_tier": "$AKS_SKU_TIER", "aks_kubernetes_version": "$KUBERNETES_VERSION", "aks_network_policy": "$NETWORK_POLICY", "aks_network_dataplane": "$NETWORK_DATAPLANE", "k8s_machine_type": "$K8S_MACHINE_TYPE", "k8s_os_disk_type": "$K8S_OS_DISK_TYPE", "aks_custom_headers": ["$AKS_CLI_CUSTOM_HEADERS"], "aks_cli_system_node_pool": "$SYSTEM_NODE_POOL", "aks_cli_user_node_pool": "$USER_NODE_POOL"}}}"
+        echo "##vso[task.setvariable variable=TERRAFORM_REGIONAL_CONFIG]{"eastus2": {"TERRAFORM_INPUT_VARIABLES": {"run_id": "$(RUN_ID)", "region": "eastus2", "aks_sku_tier": "$AKS_SKU_TIER", "aks_kubernetes_version": "$KUBERNETES_VERSION", "aks_network_policy": "$NETWORK_POLICY", "aks_network_dataplane": "$NETWORK_DATAPLANE", "k8s_machine_type": "$K8S_MACHINE_TYPE", "k8s_os_disk_type": "$K8S_OS_DISK_TYPE", "aks_custom_headers": ["$AKS_CLI_CUSTOM_HEADERS"], "aks_cli_system_node_pool": "$SYSTEM_NODE_POOL", "aks_cli_user_node_pool": "$USER_NODE_POOL"}}}"
         echo "Regional configuration set successfully."
       displayName: Set Terraform Input Variables
       condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
     - script: |-
         set -e
-        echo "Terraform Regional Config: $TERRAFORM_REGIONAL_CONFIG"
 
         terraform_input_file=$(echo $TERRAFORM_REGIONAL_CONFIG | jq -r --arg region "eastus2" '.[$region].TERRAFORM_INPUT_FILE')
 
@@ -99,7 +115,7 @@ stages:
         set -eu
         echo "Create resource group $RUN_ID in region eastus2"
         az group create --name $RUN_ID --location eastus2 \
-        --tags "run_id=$RUN_ID" "scenario=${SCENARIO_TYPE}-${SCENARIO_NAME}" "owner=${OWNER}" "creation_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "deletion_due_time=${DELETION_DUE_TIME}" "SkipAKSCluster=1"
+        --tags "run_id=$RUN_ID" "scenario=perf-eval-job-scheduling" "owner=${OWNER}" "creation_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "deletion_due_time=${DELETION_DUE_TIME}" "SkipAKSCluster=1"
       displayName: Create Resource Group
       condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
     - script: |-
@@ -176,6 +192,50 @@ stages:
 
         done
       displayName: Run Terraform Init Command
+      env:
+        ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
+      condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+      retryCountOnTaskFailure: 3
+    - script: |-
+        set -e
+
+        # Navigate to the Terraform working directory
+        cd $TERRAFORM_WORKING_DIRECTORY
+
+        for region in $(echo "['eastus2']" | jq -r '.[]'); do
+            echo "Processing region: $region"
+
+            if terraform workspace list | grep -q "$region"; then
+                terraform workspace select $region
+            else:
+                terraform workspace new $region
+                terraform workspace select $region
+            fi
+
+            # Retrieve input file and variables
+            terraform_input_file=$(echo $TERRAFORM_REGIONAL_CONFIG | jq -r --arg region "$region" '.[$region].TERRAFORM_INPUT_FILE')
+            terraform_input_variables=$(echo $TERRAFORM_REGIONAL_CONFIG | jq -r --arg region "$region" '.[$region].TERRAFORM_INPUT_VARIABLES')
+
+            # Run Terraform apply command
+            set +e
+            terraform apply --auto-approve  -var-file $terraform_input_file -var json_input="$terraform_input_variables"
+            exit_code=$?
+            set -e
+
+            # Handle errors
+            if [[ $exit_code -ne 0 ]]; then
+                echo "Terraform apply failed for region: $region"
+
+                echo "Deleting resources and removing state file before retrying"
+                ids=$(az resource list --location $region --resource-group $RUN_ID --query [*].id -o tsv)
+                az resource delete --ids $ids --verbose
+                rm -r terraform.tfstate.d/$region
+
+                exit 1
+            fi
+
+        done
+      displayName: Run Terraform Apply Command
       env:
         ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
       condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
