nodepool scale retry

diff --git a/steps/engine/clusterloader2/swiftv2/scale-cluster.yml b/steps/engine/clusterloader2/swiftv2/scale-cluster.yml
--- a/steps/engine/clusterloader2/swiftv2/scale-cluster.yml
+++ b/steps/engine/clusterloader2/swiftv2/scale-cluster.yml
@@ -36,7 +36,21 @@ steps:
       # disable autoscaler before scaling nodepool to desire node count
       az aks nodepool update --cluster-name $aks_name --name $np --resource-group $aks_rg --disable-cluster-autoscaler
       if [ "$currentnodes" != "${{ parameters.nodes_per_nodepool }}" ]; then
-        az aks nodepool scale --cluster-name $aks_name --name $np --resource-group $aks_rg -c ${{ parameters.nodes_per_nodepool }}
+
+        for i in {1..5}; do
+          if az aks nodepool scale --cluster-name $aks_name --name $np --resource-group $aks_rg -c ${{ parameters.nodes_per_nodepool }}; then
+            echo "Nodepool $np scaled successfully."
+            break
+          else
+            echo "Failed to scale nodepool $np. Retrying in 30 seconds... (Attempt $i of 5)"
+            sleep 30
+          fi
+          if [ $i -eq 5 ]; then
+            echo "##vso[task.logissue type=error;] Failed to scale nodepool $np after 5 attempts."
+            exit 1
+          fi
+        done
+
       fi
 
       # turn on autoscaler if test necessitates it
