Add installation step for kubelogin in validate-resources.yml

diff --git a/steps/topology/cluster-automatic/validate-resources.yml b/steps/topology/cluster-automatic/validate-resources.yml
--- a/steps/topology/cluster-automatic/validate-resources.yml
+++ b/steps/topology/cluster-automatic/validate-resources.yml
@@ -11,6 +11,15 @@ steps:
   parameters:
     role: automatic
     region: ${{ parameters.regions[0] }}
+- name: Install kubelogin
+  script: |
+    set -eo pipefail
+    if ! command -v kubelogin &> /dev/null; then
+      echo "kubelogin could not be found. Installing kubelogin..."
+      brew install Azure/kubelogin/kubelogin
+    fi
+    # Converts the kubeconfig to use Azure CLI authentication for AKS cluster access
+    kubelogin convert-kubeconfig -l azurecli
 - template: /steps/engine/aks-store-demo/single-cluster/configure-demo.yml
   parameters:
     action: apply
