Add terraform setup to pypeline (#634)
- Add terraform setup to pypeline
- modify gitignore to only ignore cache files

diff --git a/pypeline/generated/controller/job_scheduling.yaml b/pypeline/generated/controller/job_scheduling.yaml
--- a/pypeline/generated/controller/job_scheduling.yaml
+++ b/pypeline/generated/controller/job_scheduling.yaml
@@ -1,5 +1,5 @@
 stages:
-- displayName: eastus
+- displayName: azure-eastus2
   jobs:
   - job: setup
     displayName: Setup resources
@@ -54,6 +54,51 @@ stages:
       env:
         REGION: eastus
         AZURE_SP_SUBSCRIPTION_ID: null
+    - displayName: Set Terraform Working Directory
+      script: |-
+        echo "##vso[task.setvariable variable=TERRAFORM_WORKING_DIRECTORY]$(Pipeline.Workspace)/s/modules/terraform/azure"
+        echo "Terraform Working Directory: $(Pipeline.Workspace)/s/modules/terraform/azure"
+    - displayName: Set Terraform Input File
+      script: |-
+        set -eu
+
+        echo "##vso[task.setvariable variable=MULTI_REGION]false"
+        echo "##vso[task.setvariable variable=REGIONAL_CONFIG]{"eastus2": {"TERRAFORM_INPUT_FILE": "$(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/terraform-inputs/azure.tfvars"}}"
+      condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+    - displayName: Set User Data Path
+      script: |-
+        echo $(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/scripts/user_data
+
+        if [ -d "$(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/scripts/user_data" ]; then
+            echo "Terraform user data path exists: $(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/scripts/user_data"
+            echo "##vso[task.setvariable variable=TERRAFORM_USER_DATA_PATH]$(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/scripts/user_data"
+        else:
+            echo "Terraform user data path does not exist: $(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/scripts/user_data"
+        fi
+    - displayName: Get Deletion Due Time and Owner
+      script: |-
+        set -e
+
+        terraform_input_file=$(echo $TERRAFORM_REGIONAL_CONFIG | jq -r --arg region "eastus2" '.[$region].TERRAFORM_INPUT_FILE')
+
+        deletion_delay=$(grep 'deletion_delay' "$terraform_input_file" | awk -F'=' '{gsub(/^[ \t]+|[ \t]+$/, "", $2); gsub(/[^0-9]/, "", $2); print $2}')
+        echo "Deletion Delay: $deletion_delay hr"
+
+        deletion_due_time=$(date -u -d "+${deletion_delay} hour" +'%Y-%m-%dT%H:%M:%SZ')
+        echo "Deletion Due Time: $deletion_due_time"
+        echo "##vso[task.setvariable variable=DELETION_DUE_TIME]$deletion_due_time"
+
+        owner=$(grep 'owner' "$terraform_input_file" | awk -F'=' '{gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}' | sed 's/^"//;s/"$//')
+        echo "Owner: $owner"
+        echo "##vso[task.setvariable variable=OWNER]$owner"
+      condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+    - displayName: Create Resource Group
+      script: |-
+        set -eu
+        echo "Create resource group $RUN_ID in region eastus2"
+        az group create --name $RUN_ID --location eastus2             --tags "run_id=$RUN_ID" "scenario=${SCENARIO_TYPE}-${SCENARIO_NAME}" "owner=${OWNER}" "creation_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "deletion_due_time=${DELETION_DUE_TIME}" "SkipAKSCluster=1"
+      condition: and(eq('azure', 'azure'), ne(variables['SKIP_RESOURCE_MANAGEMENT'],
+        'true'))
     - displayName: Check Dependencies
       script: |
         python3 --version && pip3 --version
@@ -91,6 +136,14 @@ stages:
   - job: validate
     displayName: Validate resources
     steps:
+    - displayName: Validate OWNER info
+      script: |-
+        # Check if OWNER has been set to any string value other than an empty string
+        if [ -z "$OWNER" ]; then
+            echo "##vso[task.logissue type=error;] OWNER is not set. Please set OWNER to a valid value ('aks', 'compute', 'networking', 'storage') in the pipeline."
+            exit 1
+        fi
+      condition: eq(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
     - displayName: Validate SSH Key
       script: |-
         set -eu
