Add terraform to pypeline

diff --git a/pypeline/generated/controller/job_scheduling.yaml b/pypeline/generated/controller/job_scheduling.yaml
--- a/pypeline/generated/controller/job_scheduling.yaml
+++ b/pypeline/generated/controller/job_scheduling.yaml
@@ -1,5 +1,5 @@
 stages:
-- displayName: eastus
+- displayName: azure-eastus2
   jobs:
   - job: setup
     displayName: Setup resources
@@ -88,9 +88,139 @@ stages:
         cat $SSH_KEY_PATH
         echo "##vso[task.setvariable variable=SSH_KEY_PATH;]${SSH_KEY_PATH}"
       condition: eq(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+    - displayName: Set Terraform Working Directory
+      script: |-
+        echo "##vso[task.setvariable variable=TERRAFORM_WORKING_DIRECTORY]$(Pipeline.Workspace)/s/modules/terraform/azure"
+        echo "Terraform Working Directory: $(Pipeline.Workspace)/s/modules/terraform/azure"
+    - displayName: Set Terraform Input File
+      script: |-
+        set -eu
+
+        echo "##vso[task.setvariable variable=MULTI_REGION]false"
+        echo "##vso[task.setvariable variable=REGIONAL_CONFIG]{"eastus2": {"TERRAFORM_INPUT_FILE": "$(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/terraform-inputs/azure.tfvars"}}"
+      condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+    - displayName: Set User Data Path
+      script: |-
+        echo $(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/scripts/user_data
+
+        if [ -d "$(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/scripts/user_data" ]; then
+            echo "Terraform user data path exists: $(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/scripts/user_data"
+            echo "##vso[task.setvariable variable=TERRAFORM_USER_DATA_PATH]$(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/scripts/user_data"
+        else:
+            echo "Terraform user data path does not exist: $(Pipeline.Workspace)/s/scenarios/$SCENARIO_TYPE/$SCENARIO_NAME/scripts/user_data"
+        fi
+    - displayName: Set Terraform Input Variables
+      script: |-
+        set -e
+        if [[ "${DEBUG,,}" =~ "true" ]]; then
+            set -x
+        fi
+        echo "##vso[task.setvariable variable=TERRAFORM_REGIONAL_CONFIG]{"eastus2": {"TERRAFORM_INPUT_VARIABLES": {"run_id": "$(RUN_ID)", "region": "eastus2", "aks_sku_tier": "$AKS_SKU_TIER", "aks_kubernetes_version": "$KUBERNETES_VERSION", "aks_network_policy": "$NETWORK_POLICY", "aks_network_dataplane": "$NETWORK_DATAPLANE", "k8s_machine_type": "$K8S_MACHINE_TYPE", "k8s_os_disk_type": "$K8S_OS_DISK_TYPE", "aks_custom_headers": ["$AKS_CLI_CUSTOM_HEADERS"], "aks_cli_system_node_pool": "$SYSTEM_NODE_POOL", "aks_cli_user_node_pool": "$USER_NODE_POOL"}}}"
+        echo "Regional configuration set successfully."
+      condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+    - displayName: Get Deletion Due Time and Owner
+      script: |-
+        set -e
+
+        terraform_input_file=$(echo $TERRAFORM_REGIONAL_CONFIG | jq -r --arg region "eastus2" '.[$region].TERRAFORM_INPUT_FILE')
+
+        deletion_delay=$(grep 'deletion_delay' "$terraform_input_file" | awk -F'=' '{gsub(/^[ \t]+|[ \t]+$/, "", $2); gsub(/[^0-9]/, "", $2); print $2}')
+        echo "Deletion Delay: $deletion_delay hr"
+
+        deletion_due_time=$(date -u -d "+${deletion_delay} hour" +'%Y-%m-%dT%H:%M:%SZ')
+        echo "Deletion Due Time: $deletion_due_time"
+        echo "##vso[task.setvariable variable=DELETION_DUE_TIME]$deletion_due_time"
+
+        owner=$(grep 'owner' "$terraform_input_file" | awk -F'=' '{gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}' | sed 's/^"//;s/"$//')
+        echo "Owner: $owner"
+        echo "##vso[task.setvariable variable=OWNER]$owner"
+      condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+    - displayName: Create Resource Group
+      script: |-
+        set -eu
+        echo "Create resource group $RUN_ID in region eastus2"
+        az group create --name $RUN_ID --location eastus2                 --tags "run_id=$RUN_ID" "scenario=${SCENARIO_TYPE}-${SCENARIO_NAME}" "owner=${OWNER}" "creation_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "deletion_due_time=${DELETION_DUE_TIME}" "SkipAKSCluster=1"
+      condition: and(eq('azure', 'azure'), ne(variables['SKIP_RESOURCE_MANAGEMENT'],
+        'true'))
+    - displayName: Run Terraform Version Command
+      script: |-
+        set -e
+
+        # Navigate to the Terraform working directory
+        cd $TERRAFORM_WORKING_DIRECTORY
+
+        # Run Terraform version command
+        terraform version
+      env:
+        ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
+      condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+      retryCountOnTaskFailure: 3
+    - displayName: Run Terraform Init Command
+      script: |-
+        set -e
+
+        # Navigate to the Terraform working directory
+        cd $TERRAFORM_WORKING_DIRECTORY
+
+        # Run Terraform init command
+        terraform init
+      env:
+        ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
+      condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+      retryCountOnTaskFailure: 3
+    - displayName: Run Terraform Apply Command
+      script: |-
+        set -e
+
+        # Navigate to the Terraform working directory
+        cd $TERRAFORM_WORKING_DIRECTORY
+
+        for region in $(echo "['eastus2']" | jq -r '.[]'); do
+            echo "Processing region: $region"
+
+            if terraform workspace list | grep -q "$region"; then
+              terraform workspace select $region
+            else
+              terraform workspace new $region
+              terraform workspace select $region
+            fi
+
+            # Retrieve input file and variables
+            terraform_input_file=$(echo $TERRAFORM_REGIONAL_CONFIG | jq -r --arg region "$region" '.[$region].TERRAFORM_INPUT_FILE')
+            terraform_input_variables=$(echo $TERRAFORM_REGIONAL_CONFIG | jq -r --arg region "$region" '.[$region].TERRAFORM_INPUT_VARIABLES')
+
+            # Run Terraform apply command
+            set +e
+            terraform apply --auto-approve  -var-file $terraform_input_file -var json_input="$terraform_input_variables"
+            exit_code=$?
+            set -e
+
+            # Handle errors
+            if [[ $exit_code -ne 0 ]]; then
+                echo "Terraform apply failed for region: $region"
+                echo "Deleting resources and removing state file before retrying"
+                ids=$(az resource list --location $region --resource-group $RUN_ID --query [*].id -o tsv)
+                az resource delete --ids $ids --verbose
+                rm -r terraform.tfstate.d/$region
+                exit 1
+            fi
+
+        done
+      env:
+        ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
+      condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+      retryCountOnTaskFailure: 3
   - job: validate
     displayName: Validate resources
     steps:
+    - displayName: Validate OWNER info
+      script: |-
+        # Check if OWNER has been set to any string value other than an empty string
+        if [ -z "$OWNER" ]; then
+            echo "##vso[task.logissue type=error;] OWNER is not set. Please set OWNER to a valid value ('aks', 'compute', 'networking', 'storage') in the pipeline."
+            exit 1
+        fi
+      condition: eq(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
     - displayName: Validate SSH Key
       script: |-
         set -eu
