remove extra bracket cause error in generating

diff --git a/pypeline/generated/controller/job_scheduling.yaml b/pypeline/generated/controller/job_scheduling.yaml
--- a/pypeline/generated/controller/job_scheduling.yaml
+++ b/pypeline/generated/controller/job_scheduling.yaml
@@ -275,20 +275,19 @@ stages:
             exit 1
         fi
       condition: eq(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
-    - !!python/tuple
-      - displayName: Validate Installed Dependencies
-        script: |-
-          set -e
+    - displayName: Validate Installed Dependencies
+      script: |-
+        set -e
 
-          # Check if requirements.txt exists
-          echo "Validating installed dependencies..."
-          missing_dependencies=$(pip3 check 2>&1 | grep -i "not found" || true)
-          if [ -n "$missing_dependencies" ]; then
-              echo "Error: Missing dependencies:"
-              echo "$missing_dependencies"
-              exit 1
-          fi
-          echo "All dependencies are installed."
+        # Check if requirements.txt exists
+        echo "Validating installed dependencies..."
+        missing_dependencies=$(pip3 check 2>&1 | grep -i "not found" || true)
+        if [ -n "$missing_dependencies" ]; then
+            echo "Error: Missing dependencies:"
+            echo "$missing_dependencies"
+            exit 1
+        fi
+        echo "All dependencies are installed."
     - displayName: Validate SSH Key
       script: |-
         set -eu
