add validate and tear down for python

diff --git a/pypeline/generated/controller/job_scheduling.yaml b/pypeline/generated/controller/job_scheduling.yaml
--- a/pypeline/generated/controller/job_scheduling.yaml
+++ b/pypeline/generated/controller/job_scheduling.yaml
@@ -275,6 +275,20 @@ stages:
             exit 1
         fi
       condition: eq(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+    - !!python/tuple
+      - displayName: Validate Installed Dependencies
+        script: |-
+          set -e
+
+          # Check if requirements.txt exists
+          echo "Validating installed dependencies..."
+          missing_dependencies=$(pip3 check 2>&1 | grep -i "not found" || true)
+          if [ -n "$missing_dependencies" ]; then
+              echo "Error: Missing dependencies:"
+              echo "$missing_dependencies"
+              exit 1
+          fi
+          echo "All dependencies are installed."
     - displayName: Validate SSH Key
       script: |-
         set -eu
@@ -307,6 +321,19 @@ stages:
     - validate
   - job: tear down
     displayName: Tear down resources
-    steps: []
+    steps:
+    - displayName: Uninstall Python Dependencies
+      script: |-
+        set -e
+
+        echo "Uninstalling Python dependencies listed in requirements.txt..."
+        xargs -a "$(Pipeline.Workspace)/s/modules/python/requirements.txt" -n 1 pip3 uninstall -y
+    - displayName: Delete Python Cache
+      script: |-
+        set -e
+
+        echo "Deleting Python cache..."
+        rm -rf "$(Pipeline.Workspace)/s/modules/python/__pycache__"
+        echo "Python environment cleanup completed."
     dependsOn:
     - run
