update karpenter module

diff --git a/steps/engine/clusterloader2/autoscale/collect.yml b/steps/engine/clusterloader2/autoscale/collect.yml
--- a/steps/engine/clusterloader2/autoscale/collect.yml
+++ b/steps/engine/clusterloader2/autoscale/collect.yml
@@ -13,20 +13,26 @@ steps:
     kubectl delete --all nodeclaim --ignore-not-found
     kubectl delete --all nodepool --ignore-not-found
 
-    # Get all nodes with the Karpenter nodepool label
-    NODES=$(kubectl get nodes -l karpenter.sh/nodepool -o jsonpath='{.items[*].metadata.name}')
-
-    # Loop through each node to extract the instance ID and terminate
-    for NODE in $NODES; do
-      INSTANCE_ID=$(kubectl get node "$NODE" -o json | jq -r '.spec.providerID' | cut -d '/' -f5)
-
-      # Terminate the EC2 instance
-      if [ -n "$INSTANCE_ID" ]; then
-        echo "Terminating instance: $INSTANCE_ID"
-        aws ec2 terminate-instances --instance-ids "$INSTANCE_ID"
-      fi
+    echo "Delete all the network interfaces"
+    subnet_ids=$(aws ec2 describe-subnets --query "Subnets[?Tags[?Key=='run_id' && Value=='$RUN_ID']].SubnetId" --output text)
+    for subnet_id in $subnet_ids; do
+      echo "Detaching Subnet: $subnet_id Network Interfaces ..."
+      network_interfaces_attachment_id=$(aws ec2 describe-network-interfaces --filters Name=subnet-id,Values=$subnet_id --query "NetworkInterfaces[].Attachment.AttachmentId" --output text)
+      for network_interface_attachment_id in $network_interfaces_attachment_id; do
+        echo "Detaching Network Interface attachment id: $network_interface_attachment_id"
+        if ! aws ec2 detach-network-interface --attachment-id $network_interface_attachment_id; then
+          echo "##vso[task.logissue type=error;] Failed to detach Network Interface attachment id: $network_interface_attachment_id"
+        fi
+      done      
+      network_interfaces=$(aws ec2 describe-network-interfaces --filters Name=subnet-id,Values=$subnet_id --query "NetworkInterfaces[].NetworkInterfaceId" --output text)
+      for network_interface in $network_interfaces; do
+        echo "Deleting Network Interface: $network_interface"
+        if ! aws ec2 delete-network-interface --network-interface-id $network_interface; then
+          echo "##vso[task.logissue type=error;] Failed to delete Network Interface: $network_interface"
+        fi
+      done
     done
-  displayName: "Delete NodeClaim. NodePool and Terminate EC2 Instances"
+  displayName: "Delete NodeClaim, NodePool and Network Interfaces"
   condition: always()
 - template: /steps/cloud/${{ parameters.cloud }}/collect-cloud-info.yml
   parameters:
