Fail a task if SKIP_RESOURCE_DELETION is set to true

diff --git a/steps/terraform/run-command.yml b/steps/terraform/run-command.yml
--- a/steps/terraform/run-command.yml
+++ b/steps/terraform/run-command.yml
@@ -16,13 +16,19 @@ parameters:
 - name: credential_type
   type: string
   default: 'managed_identity'
-- name: condition
-  type: string
-  default: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
+- name: skip_resource_deletion
+  type: boolean
+  default: false
 
 steps:
 - script: |
     set -e
+
+    if [[ "${parameter.skip_resource_deletion}" == "true" ]]; then
+      echo "##vso[task.logissue type=error;] SKIP_RESOURCE_DELETION is true. Please delete resource manually.
+    terraform ${{ parameters.command }} --auto-approve ${{ parameters.arguments }} -var-file $terraform_input_file -var json_input="$terraform_input_variables" | tee terraform_${{ parameters.command }}.log"
+      exit 1
+    fi
 
     cd $TERRAFORM_WORKING_DIRECTORY
     if [[ ${{ parameters.command }} == "apply" || ${{ parameters.command }} == "destroy" ]]; then
@@ -84,7 +90,7 @@ steps:
       terraform ${{ parameters.command }} ${{ parameters.arguments }}
     fi
   displayName: "Run Terraform ${{ parameters.command }} Command"
-  condition: ${{ parameters.condition }}
+  condition: ne(variables['SKIP_RESOURCE_MANAGEMENT'], 'true')
   retryCountOnTaskFailure: ${{ parameters.retry_attempt_count }}
   env:
     REGIONS: ${{ convertToJson(parameters.regions) }}
