move skip deletion check

diff --git a/steps/terraform/run-command.yml b/steps/terraform/run-command.yml
--- a/steps/terraform/run-command.yml
+++ b/steps/terraform/run-command.yml
@@ -24,15 +24,6 @@ steps:
 - script: |
     set -e
 
-    echo "Terraform Input File: $terraform_input_file"
-    echo "Terraform Input Variables: $terraform_input_variables"
-
-    if [[ "${{ parameters.skip_resource_deletion }}" == "true" ]]; then
-      echo "##vso[task.logissue type=error;] SKIP_RESOURCE_DELETION is true. Please delete resource manually.
-    terraform ${{ parameters.command }} --auto-approve ${{ parameters.arguments }} -var-file $terraform_input_file -var json_input="$terraform_input_variables" | tee terraform_${{ parameters.command }}.log"
-      exit 1
-    fi
-
     cd $TERRAFORM_WORKING_DIRECTORY
     if [[ ${{ parameters.command }} == "apply" || ${{ parameters.command }} == "destroy" ]]; then
       for region in $(echo "$REGIONS" | jq -r '.[]'); do
@@ -44,6 +35,12 @@ steps:
         fi
         terraform_input_file=$(echo $TERRAFORM_REGIONAL_CONFIG | jq -r --arg region "$region" '.[$region].TERRAFORM_INPUT_FILE')
         terraform_input_variables=$(echo $TERRAFORM_REGIONAL_CONFIG | jq -r --arg region "$region" '.[$region].TERRAFORM_INPUT_VARIABLES')
+
+        if [[ "${{ parameters.skip_resource_deletion }}" == "true" ]]; then
+          echo "##vso[task.logissue type=error;] SKIP_RESOURCE_DELETION is true. Please delete resource manually.
+    terraform ${{ parameters.command }} --auto-approve ${{ parameters.arguments }} -var-file $terraform_input_file -var json_input="$terraform_input_variables" | tee terraform_${{ parameters.command }}.log"
+          exit 1
+        fi
 
         set +e
         terraform ${{ parameters.command }} --auto-approve ${{ parameters.arguments }} -var-file $terraform_input_file -var json_input="$terraform_input_variables" | tee terraform_${{ parameters.command }}.log
