Test

diff --git a/steps/cleanup-resources.yml b/steps/cleanup-resources.yml
--- a/steps/cleanup-resources.yml
+++ b/steps/cleanup-resources.yml
@@ -15,22 +15,27 @@ parameters:
   default: managed_identity
 
 steps:
-- template: /steps/terraform/run-command.yml
-  parameters:
-    command: destroy
-    arguments: ${{ parameters.terraform_arguments }}
-    regions: ${{ parameters.regions }}
-    cloud: ${{ parameters.cloud }}
-    retry_attempt_count: ${{ parameters.retry_attempt_count }}
-    credential_type: ${{ parameters.credential_type }}
-    skip_resource_deletion: "${SKIP_RESOURCE_DELETION}"
+# - template: /steps/terraform/run-command.yml
+#   parameters:
+#     command: destroy
+#     arguments: ${{ parameters.terraform_arguments }}
+#     regions: ${{ parameters.regions }}
+#     cloud: ${{ parameters.cloud }}
+#     retry_attempt_count: ${{ parameters.retry_attempt_count }}
+#     credential_type: ${{ parameters.credential_type }}
+#     skip_resource_deletion: "${SKIP_RESOURCE_DELETION}"
 
 - script: |
     set -eu
 
+    echo $VALIDATION_FAILED
     if [[ "${SKIP_RESOURCE_DELETION:-false}" == "true" && "$BUILD_REASON" == "Manual" ]]; then
       echo "##vso[task.logissue type=error;] SKIP_RESOURCE_DELETION is set. Please delete resource group manually.
-    az group delete --name $RUN_ID --yes"
+      exit 1
+    fi
+
+    if [[ "$VALIDATION_FAILED" == "true" ]]; then
+      echo "##vso[task.logissue type=error;] Validation failed. Please delete resource group manually."
       exit 1
     fi
 
diff --git a/steps/engine/clusterloader2/slo/validate.yml b/steps/engine/clusterloader2/slo/validate.yml
--- a/steps/engine/clusterloader2/slo/validate.yml
+++ b/steps/engine/clusterloader2/slo/validate.yml
@@ -11,8 +11,12 @@ steps:
 
       PYTHONPATH=$PYTHONPATH:$(pwd) python3 $PYTHON_SCRIPT_FILE validate \
         $DESIRED_NODES $VALIDATION_TIMEOUT_IN_MINUTES
+      if [ $? -ne 0 ]; then
+        echo "##vso[task.setvariable variable=VALIDATION_FAILED;isOutput=true]true"
+        exit 1
+      fi
     workingDirectory: modules/python
-    timeoutInMinutes: ${{ parameters.validation_timeout_in_minutes }}
+    timeoutInMinutes: 15
     displayName: "Validate node count"
     env:
       DESIRED_NODES: ${{ parameters.desired_nodes }}
