fix script issues during creation and deletion

diff --git a/steps/cleanup-resources.yml b/steps/cleanup-resources.yml
--- a/steps/cleanup-resources.yml
+++ b/steps/cleanup-resources.yml
@@ -27,7 +27,7 @@ steps:
     set -eu
     for attempt in $(seq 1 5); do
       echo "Attempting to execute subnetdelegator DELETE command: $attempt/5"
-      script --return --quiet -c "az containerapp exec -n subnetdelegator-westus-u3h4j -g subnetdelegator-westus --command 'curl -X DELETE http://localhost:8080/DelegatedSubnet/%2Fsubscriptions%2F9b8218f9-902a-4d20-a65c-e98acec5362f%2FresourceGroups%2F$RUN_ID%2Fproviders%2FMicrosoft.Network%2FvirtualNetworks%2F$2Fcustvnet%2Fsubnets%2F$2Fdelgpod'" /dev/null && break || echo "Command failed, retrying..."
+      script --return --quiet -c "az containerapp exec -n subnetdelegator-westus-u3h4j -g subnetdelegator-westus --command 'curl -X DELETE http://localhost:8080/DelegatedSubnet/%2Fsubscriptions%2F9b8218f9-902a-4d20-a65c-e98acec5362f%2FresourceGroups%2F$RUN_ID%2Fproviders%2FMicrosoft.Network%2FvirtualNetworks%2Fcustvnet%2Fsubnets%2Fscaledel'" /dev/null && break || echo "Command failed, retrying..."
       sleep 30
     done
   displayName: "Delete SAL Ping"
